---
# tasks file for gitconfig
- name: mkdir repo's parent directory
  file:
    path: "{{gitconfig_cloned_dest|dirname}}"
    state: directory
- name: Clone the gitconfig repository
  git:
    repo: "{{gitconfig_repo}}"
    dest: "{{gitconfig_cloned_dest}}"
    version: "{{gitconfig_version}}"
- name: Make symbolic link
  file:
    src: "{{gitconfig_cloned_dest}}/{{gitconfig_src}}"
    dest: "{{ansible_env.HOME}}/.gitconfig"
    state: link
