---
# tasks file for gitconfig
- name: ghq root
  shell: "{{gitconfig_ghq_executable}} root"
  register: ghq_root
  changed_when: false
- name: Clone gitconfig repository
  ghq:
    name: "{{remote_repository_path}}"
    executable: "{{gitconfig_ghq_executable}}"
- name: Make symbolic links
  file:
    src: "{{ghq_root.stdout}}/github.com/{{remote_repository_path}}/.gitconfig"
    dest: "{{ansible_env.HOME}}/.gitconfig"
    state: link
